# Generated by Django 5.0.1 on 2024-03-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(default='')),
                ('image', models.ImageField(null=True, upload_to='static/images/albums', verbose_name='Image')),
                ('release_date', models.DateField(verbose_name='Relase Date')),
                ('num_stars', models.IntegerField(verbose_name='Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(default='')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(default='')),
                ('lyric', models.TextField(blank=True, null=True, verbose_name='Lyric')),
                ('music_url', models.URLField(blank=True, null=True, verbose_name='Music Path')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image Path')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video Path')),
                ('release_date', models.DateField(verbose_name='Relase Date')),
                ('num_stars', models.IntegerField(verbose_name='Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('avatar', models.ImageField(null=True, upload_to='static/images/avatars', verbose_name='Avatar')),
                ('slug', models.SlugField(default='')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Resume')),
            ],
        ),
    ]
