# Generated by Django 5.0.1 on 2024-03-22 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.album', verbose_name=''),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ManyToManyField(to='musics.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='list',
            name='musics',
            field=models.ManyToManyField(to='musics.music', verbose_name='Musics'),
        ),
        migrations.AddField(
            model_name='musician',
            name='category',
            field=models.ManyToManyField(to='musics.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.musician', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.musician', verbose_name='Artist'),
        ),
    ]
