# Generated by Django 5.0.1 on 2024-03-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(to='musics.album', verbose_name=''),
        ),
    ]
