# Generated by Django 5.0.1 on 2024-03-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_remove_music_album_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, to='musics.album', verbose_name=''),
        ),
    ]
