# Generated by Django 5.0.1 on 2024-01-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_image_url_alter_music_lyric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='relase_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
