# Generated by Django 5.0.1 on 2024-03-28 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, to='musics.album', verbose_name='Albums'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.musician', verbose_name='Artists'),
        ),
    ]
