# Generated by Django 5.0.1 on 2024-03-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_alter_music_album_alter_music_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album',
            new_name='albums',
        ),
    ]
