# Generated by Django 5.0.1 on 2024-03-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_rename_album_music_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='feats',
            field=models.ManyToManyField(blank=True, to='musics.musician', verbose_name='Feats'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_artist', to='musics.musician', verbose_name='Artists'),
        ),
    ]
