# Generated by Django 5.0.1 on 2024-01-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images', verbose_name='Avatar'),
        ),
    ]
