# Generated by Django 5.0.1 on 2024-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_alter_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='feats', to='musics.musician', verbose_name='Feats'),
        ),
    ]
