# Generated by Django 5.0.1 on 2024-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_image_alter_musician_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='music.musician', verbose_name='Artist'),
        ),
    ]
