# Generated by Django 5.0.1 on 2024-04-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_alter_music_feats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image Path'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Music Path'),
        ),
        migrations.AlterField(
            model_name='music',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Video Path'),
        ),
    ]
