# Generated by Django 5.0.1 on 2024-03-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_music_artist_music_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Artist'),
            preserve_default=False,
        ),
    ]
