# Generated by Django 5.0.1 on 2024-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_music_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='avatar',
            field=models.URLField(max_length=500, verbose_name='Avatar'),
        ),
    ]
