# Generated by Django 5.0.1 on 2024-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0013_alter_musician_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(max_length=500, verbose_name='Image'),
        ),
    ]
