# Generated by Django 5.0.1 on 2024-01-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(default='')),
                ('relase_date', models.DateField(verbose_name='Relase Date')),
                ('num_stars', models.IntegerField(verbose_name='Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('slug', models.SlugField(default='')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Resume')),
                ('category', models.ManyToManyField(to='music.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(default='')),
                ('lyric', models.TextField(null=True, verbose_name='Lyric')),
                ('music_url', models.URLField(verbose_name='Music Path')),
                ('image_url', models.URLField(verbose_name='Image Path')),
                ('video_url', models.URLField(verbose_name='Video Path')),
                ('relase_date', models.DateField(verbose_name='Relase Date')),
                ('num_stars', models.IntegerField(verbose_name='Stars')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='')),
                ('category', models.ManyToManyField(to='music.category', verbose_name='Category')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Artist'),
        ),
    ]
