# Generated by Django 5.0.1 on 2024-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image Path'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyric',
            field=models.TextField(blank=True, null=True, verbose_name='Lyric'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_url',
            field=models.URLField(blank=True, null=True, verbose_name='Music Path'),
        ),
        migrations.AlterField(
            model_name='music',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Path'),
        ),
    ]
