# Generated by Django 5.0.1 on 2024-01-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Image'),
        ),
    ]
