# Generated by Django 5.0.1 on 2024-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_musician_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/albums', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images/avatars', verbose_name='Avatar'),
        ),
    ]
